# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления #user b209003097268429d166f641bd52d9d0e639c1d8
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token b209003097268429d166f641bd52d9d0e639c1d8

{
  "title": "НОУТ3",
  "description": "Срочно"
}

###

# попытка поменять объявление 4ca2e6fab5b681e75b9d2076c85320962fc9b85f
PATCH {{baseUrl}}/advertisements/35/
Content-Type: application/json
Authorization: Token b209003097268429d166f641bd52d9d0e639c1d8

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2024-03-02
Content-Type: application/json

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token b209003097268429d166f641bd52d9d0e639c1d8

