# Generated by Django 4.2.10 on 2024-02-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_scope_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тематика', 'verbose_name_plural': 'Тематики'},
        ),
    ]
